### ISSUE TITLE
What's the License?

### ISSUE THREAD

**Issue by btopro** [samccone/fidgetspin.xyz#42]
I want to try and make this a web component (https://webcomponents.org) as I think this would be an awesome example of something interactive that people could laugh at at presentations but also grep the internals of and understand the vision of web components via a fun, non-emoji based example.

**Comment by FluorescentHallucinogen** [comment]
@samccone Please add `"license"` as well as `"authors"`, `"name"`, `"version"`, `"description"`, `"keywords"`, `"homepage"` and `"bugs"` fields to `package.json` file. :wink:

**Comment by paulirish** [comment]
license is MIT. copyright assigned to `Sam Saccone`

it'd be useful if someone could provide a PR for a license file and updating those package.json fields.

**Comment by FluorescentHallucinogen** [comment]
@paulirish PTAL at #68. :wink:
