### ISSUE TITLE
Device width is not being recognized

### ISSUE THREAD

**Issue by donroyco** [samccone/fidgetspin.xyz#6]
As stated in the index.html file, the website should take the width of the device.
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
```
However, when I check the website in Google Chrome Version 58.0.3029.113 on an iPhone 6s, the width is not being recognized (see image below). A horizontal scrollbar is visible. 

<img src="https://cloud.githubusercontent.com/assets/1763537/26647371/78eaf0c4-463f-11e7-8f35-f97f0585f153.jpg" width="50%" />
I'm not sure what's causing this problem, because when I check the website in Google Chrome (desktop) with Developer Tools responsive tool, it's showing the correct width (100% of the device width).

![fidget-spinner-chrome](https://cloud.githubusercontent.com/assets/1763537/26647437/a6c8a9d2-463f-11e7-8fb9-f647ab1fe234.png)

**Comment by samccone** [comment]
indeed, something is up in safari... still figuring it out. I added autoprefixer thinking that might do it ... but not luck

**Comment by donroyco** [comment]
True. 

The width is still off in Chrome because of this:

```CSS
#header {
  width: 100%;
  padding: 10px;
}
```

The `width` is more than 100%, adding `box-sizing: border-box;` can solve this problem.

**Comment by paulirish** [comment]
mmm border-box...​

**Comment by samccone** [comment]
fixed
